# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GeoNode Summit 2018"
email: "summit@ithacaweb.org"
description: "Website of the 2018 GeoNode Summit"
baseurl: "/geonode-summit-2018"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "AIzaSyCwKnk6AsjtdlRg-4qYVTnp-8jtXXFM89c"

# Organizer Info
organizerName: "ITHACA"
organizerAlternateName: "Information Technology for Humanitarian Assistance, Cooperation and Action"
organizerDescription: "The non-profit association ITHACA is a center of applied research devoted to support humanitarian activities in response to natural disasters by means of remote sensing techniques."
organizerEmail: "summit@ithacaweb.org"
organizerLogo: "/img/organizers/ithaca.jpg"
organizerLink: "http://www.ithacaweb.org"

# Head
metaKeywords: "event, summit, geonode, open source, programming, maps, developers, politecnico, torino, django, geoserver, postgis"
twitterAccount: "@GeoNode"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://bit.ly/2rzWEeb", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://bit.ly/2rzWEeb", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GeoNode <typeout> Summit 2018"
eventDate: "Torino, Italy | March 26 - 28, 2018"
typeoutTextValues: '"", "Dev", "Users", "World"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://bit.ly/2rzWEeb", text: "Become a speaker"}
 - {permalink: "/#register", text: "Register"}

# About Block
aboutTitle: "About GeoNode Summit"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The GeoNode event of the year with awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Improve your knowledge of GeoNode with workshops held by core developers aimed at both users and developers!" }
 - {title: "Roadmapping", image: "roadmapping.jpg", text: "One full day for an open discussion on the future of GeoNode." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "20", specialCharacter: "+", info: "hours", detail: "of GeoNode full immersion"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from everywhere"}
 - {count: "2", specialCharacter: "", info: "workshops", detail: "for users and developers"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Key speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "SiTI-ITHACA"
eventLocationLink: "http://www.ithacaweb.org/"
eventStreetAddress: "Corso Castelfidardo 30/a"
eventAddressLocality: "Torino"
eventAddressLocalityRegion: "Piemonte"
eventPostalCode: "10129"
eventAddressCountry: "Italy"
eventStartTime: "2018-03-26T09:00"
eventDoorTime: "08:30"
eventEndTime: "2018-03-28T18:00"
eventPlaceCoordinates: "45.06568, 7.65967"
mapCenterCoordinates: "45.06568, 7.65967"
mapMobileCenterCoordinates: "45.06568, 7.65967"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "SiTI/ITHACA"
venueFeatures: ["One Theatre", "One Conference Room", "Two Meeting Rooms"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "geonode"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "#"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=GeoNode", icon: "twitter"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://geonode.org", text: "GeoNode"}
   - {link: "http://https://www.osgeo.org", text: "OSGeo"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:summit@ithacaweb.org", text: "summit@ithacaweb.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/blog/how-to-get-to-the-venue", text: "How to get to the venue"}
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About"
aboutUs: "GeoNode is a web-based Spatial Data Infrastructure (SDI) that enables sharing and collaborating on geospatial data. Users can upload existing shapefiles, edit data, and publish finished maps. GeoNode can also host static documents, such as PDF maps. GeoNode has robust support for open standards and OGC services, which streamlines integration with other systems and existing workflows. For example, data from GeoNode can be easily downloaded as a shapefile for use in ArcMap. At its core, GeoNode is designed to be customizable and extensible.
GeoNode is used throughout the world by international organizations, non-profits, and mapping agencies for supporting activities ranging from emergency preparedness and response, disaster risk reduction, and many more. Additionally, GeoNode is supported by a rich ecosystem of commercial providers across the world who can help with training, technical support, or development of new features.
Whether your use case is wrangling thousands of layers or managing just 10 really well, GeoNode can help make your job easier."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Torino"
directionDetailsCards:
 - {title: "From the Airport", information: 'Torino Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.aeroportoditorino.it/en">airport website</a>.'}
 - {title: "Public Transit", information: 'Ordinary urban ticket is 1.50 €. More information about <a href="http://www.gtt.to.it/cms/en/fares">fares</a> and directions at <a href="http://www.gtt.to.it/cms/en/">GTT website</a>. The Torino Underground connects the Fermi station in Collegno through the Lingotto station in Torino. Vinzaglio is the closest station to ITHACA.'}
 - {title: "Hotels", information: 'Torino has lots of great hotels and apartments to rent. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Getting to the venue"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "At the airport"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Arriving by train"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Get around Torino"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "How to register"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Submit a presentation"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Recommended Hotels"}
     - {link: "/cod/", text: "Code of Conduct"}

# Hackathon
hackathonTitle: "Code Sprint"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
